version: 2

sources:
  - name: curated
    schema: curated
    freshness: # default freshness
      warn_after: { count: 24, period: hour }
      error_after: { count: 36, period: hour }
    loaded_at_field: load_timestamp
    tables:
      - name: job_online
      - name: job_description
      - name: job_location
